---
- name: install gitlab-ce dependencies packages
  apt:
    name: {{ packages }}
    state: latest
  vars:
    packages:
      - curl
      - openssh-server
      - ca-certificates
      - postfix

- name: get gitlab-ce installer
  get_url: url=https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh dest=/tmp/install_gitlab-ce.sh mode="a+x"

- name: install gitlab-ce
  shell: /tmp/install_gitlab-ce.sh

- name: install gitlab-ce package
  apt:
    name: {{ packages }}
    state: latest
  vars:
    packages:
      - gitlab-ce

- name: configure gitlab-ce
  shell: gitlab-ctl reconfigure

- name: show gitlab-ce credentials
  debug: msg="Default credientials are root / 5iveL!fe"
